export const ELASTICSEARCH_CLIENT_KEY = 'ELASTICSEARCH_CLIENT_KEY';

export const IMAGE_VECTORS_DIMENSIONS = 512;

export const ES_INDEX_NUMBER_OF_SHARDS = 6;

export const ES_INDEX_NUMBER_OF_REPLICAS = 2;
